# -*- coding: utf-8 -*-
"""LESSON 1: HELLO, PYTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18t-g2dLkhQxyI_xNeOd3u8ugwTm-O_U1
"""

spam_amount = 0
print(spam_amount)

# Ordering Spam, egg, Spam, Spam, bacon and Spam (4 more servings of Spam)
spam_amount = spam_amount + 4

if spam_amount > 0:
    print("But I don't want ANY spam!")

viking_song = "Spam " * spam_amount
print(viking_song)

print("You've successfully run some Python code")
print("Congratulations!")